"""
ingest_from_kaggle.py  — StoryBit Kaggle Ingestion Pipeline v6
══════════════════════════════════════════════════════════════════════
Design:
  • Each CSV row → exactly ONE Supabase document row
  • content     = natural-language sentence built from that row by LLM template
  • metadata    = {category, topic, tags, embedding_model, file, kaggle_slug,
                   author, published_at, source_from}
  • category / topic / tags are AUTO-GENERATED by LLM per dataset
    → no manual entry needed; spreadsheet only supplies slugs
  • No Wikipedia fallback — if dataset has no text it is skipped
  • LM Studio schema LLM reads compact stats (fits 2048-token context)
  • Gemini primary embedder (768-dim), nomic via LM Studio fallback
  • category / topic / source_from are GENERATED columns in Supabase
    → never inserted directly; they are computed from metadata JSONB

Table columns written on insert (writable only):
  content       TEXT          ← sentence built from this CSV row
  embedding     vector(768)   ← Gemini gemini-embedding-001 or nomic
  source_title  TEXT          ← Kaggle dataset name
  source_url    TEXT          ← kaggle.com/datasets/{slug}
  source_type   TEXT          ← reddit | twitter | news | book | youtube |
                                 social_media | web_scrape
  metadata      JSONB         ← {category, topic, tags, embedding_model,
                                  file, kaggle_slug, author,
                                  published_at, source_from}

Generated (read-only, computed by Supabase from metadata):
  category      TEXT          ← metadata->>'category'
  topic         TEXT          ← metadata->>'topic'
  source_from   TEXT          ← metadata->>'source_from'

Full pipeline (slugs from spreadsheet, metadata from LLM):
  python ingest_from_kaggle.py

Test a single dataset — no spreadsheet needed:
  python ingest_from_kaggle.py --test --slug owner/dataset-name
  python ingest_from_kaggle.py --test --slug owner/dataset-name --dry-run
  python ingest_from_kaggle.py --test --slug owner/dataset-name --limit 10

LM Studio must have loaded:
  1. lfm2.5-1.2b-instruct-thinking-claude-high-reasoning-mlx  (schema + metadata LLM)
  2. text-embedding-nomic-embed-text-v1.5                       (fallback embedder)
══════════════════════════════════════════════════════════════════════
"""

import os, re, sys, json, time, glob, hashlib, argparse, tarfile, zipfile, shutil
import httpx
import openpyxl
import pandas as pd
import nltk

from pathlib import Path
from urllib.parse import urlparse
from dotenv import load_dotenv
from supabase import create_client, Client
from google import genai
from google.genai import types as genai_types
from nltk.tokenize import sent_tokenize

load_dotenv()

for resource in ["punkt", "punkt_tab"]:
    try:
        nltk.data.find(f"tokenizers/{resource}")
    except LookupError:
        nltk.download(resource, quiet=True)


# ══════════════════════════════════════════════════════════════
# CONFIGURATION
# ══════════════════════════════════════════════════════════════

SPREADSHEET_FILE = "Storybit_Database.xlsx"
PROGRESS_FILE    = "kaggle_progress.log"

GEMINI_MODEL         = "gemini-embedding-001"
LM_STUDIO_BASE       = "http://127.0.0.1:1234"
NOMIC_MODEL_ID       = "text-embedding-nomic-embed-text-v1.5"
NOMIC_EMBED_ENDPOINT = f"{LM_STUDIO_BASE}/v1/embeddings"
NOMIC_PREFIX         = "search_document: "

BATCH_SIZE       = 100     # rows per embed+insert call
NOMIC_BATCH_SIZE = 50
MAX_ROWS_PER_DS  = 2000    # max rows extracted per dataset file
MIN_ROW_WORDS    = 8       # skip sentences shorter than this
CHUNK_WORDS      = 250     # target content chunk size (target schema)
CHUNK_OVERLAP    = 50      # overlap words between chunks
MAX_CONTENT_CHARS = 4000   # protect DB insert/embedding payload size
FAILED_ROWS_FILE  = "failed_rows.ndjson"
FAILED_DATASETS_FILE = "failed_datasets.log"
_runtime_max_rows_per_ds = MAX_ROWS_PER_DS  # 0 means no cap

_LM_CHAT_URL = f"{LM_STUDIO_BASE}/v1/chat/completions"
_LM_MODELS   = f"{LM_STUDIO_BASE}/api/v1/models"

_use_nomic   = False       # runtime state: switches permanently on Gemini quota hit


# ══════════════════════════════════════════════════════════════
# JSON SCHEMAS FOR LM STUDIO STRUCTURED OUTPUT
#
# LM Studio requires response_format with type "json_schema"
# and a full JSON Schema definition inside json_schema.schema.
# See: https://lmstudio.ai/docs/advanced/structured-output
# Schema spec: https://json-schema.org/learn/miscellaneous-examples
# ══════════════════════════════════════════════════════════════

# Schema for dataset metadata generation (category/topic/tags/objective)
_METADATA_JSON_SCHEMA = {
    "type": "json_schema",
    "json_schema": {
        "name": "dataset_metadata",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Broad domain: Politics, Technology, Science, Health, Business, Sports, Entertainment, Education, Society, or Environment"
                },
                "topic": {
                    "type": "string",
                    "description": "Specific topic of this dataset in 3-6 words"
                },
                "tags": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "3-6 keyword tags for this dataset"
                },
                "objective": {
                    "type": "string",
                    "description": "Intent like News, Analysis, Learning, Curiosity, Self improvement, Entertainment"
                }
            },
            "required": ["category", "topic", "tags", "objective"],
            "additionalProperties": False
        }
    }
}

# Schema for CSV column classification (schema analysis)
_SCHEMA_JSON_SCHEMA = {
    "type": "json_schema",
    "json_schema": {
        "name": "column_classification",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "primary": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Rich text columns with avg_words >= 8"
                },
                "context": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "Short label columns used as prefix"
                },
                "noise": {
                    "type": "array",
                    "items": {"type": "string"},
                    "description": "IDs, URLs, usernames, timestamps, scores"
                },
                "date_col": {
                    "type": "string",
                    "description": "Column holding original publish date, or empty string"
                },
                "is_social": {
                    "type": "boolean",
                    "description": "Whether this is social media data"
                },
                "dataset_type": {
                    "type": "string",
                    "description": "Type like reddit_comments, news_articles, general, etc."
                },
                "sentence_template": {
                    "type": "string",
                    "description": "Template using {column_name} placeholders"
                },
                "confidence": {
                    "type": "number",
                    "description": "Confidence score 0.0 to 1.0"
                },
                "reasoning": {
                    "type": "string",
                    "description": "One sentence explanation"
                }
            },
            "required": ["primary", "context", "noise", "date_col", "is_social",
                         "dataset_type", "sentence_template", "confidence", "reasoning"],
            "additionalProperties": False
        }
    }
}

# Schema for source type detection
_SOURCE_TYPE_JSON_SCHEMA = {
    "type": "json_schema",
    "json_schema": {
        "name": "source_type_classification",
        "strict": True,
        "schema": {
            "type": "object",
            "properties": {
                "source_type": {
                    "type": "string",
                    "enum": ["web_scrape", "news", "wikipedia", "book", "youtube"],
                    "description": "One of: web_scrape, news, wikipedia, book, youtube"
                }
            },
            "required": ["source_type"],
            "additionalProperties": False
        }
    }
}


# ══════════════════════════════════════════════════════════════
# SPREADSHEET READER
# ══════════════════════════════════════════════════════════════

def read_spreadsheet(filepath: str) -> list[dict]:
    wb   = openpyxl.load_workbook(filepath)
    ws   = wb.active
    rows = list(ws.iter_rows(values_only=True))
    if not rows:
        return []

    header = [str(c).strip().lower() if c else "" for c in rows[0]]
    col    = {}
    for i, h in enumerate(header):
        if "category" in h:                                       col["category"] = i
        elif "topic"    in h:                                     col["topic"]    = i
        elif "objective" in h:                                    col["objective"] = i
        elif "tag"      in h:                                     col["tags"]     = i
        elif "vector"   in h or "kaggle" in h or "database" in h: col["db_link"] = i

    topics = []
    for r_idx, row in enumerate(rows[1:], start=2):
        if not any(row):
            continue
        category = str(row[col.get("category", 0)] or "").strip()
        topic    = str(row[col.get("topic",    1)] or "").strip()
        objective = str(row[col.get("objective", 2)] or "").strip()
        tags_raw = str(row[col.get("tags",     2)] or "").strip()
        db_link  = str(row[col.get("db_link",  4)] or "").strip()

        if not category or not topic:
            continue

        tags: list[str] = []
        if tags_raw and tags_raw.lower() not in ("none", ""):
            try:
                parsed = json.loads(tags_raw)
                tags   = [str(t).strip() for t in parsed if t] if isinstance(parsed, list) else []
            except (json.JSONDecodeError, ValueError):
                tags = [t.strip() for t in tags_raw.split(",") if t.strip()]

        url = ""
        for line in db_link.splitlines():
            if "kaggle.com" in line.lower():
                url = line.strip()
                break

        # If the cell contains a hyperlink but no visible URL text, read link target.
        if not url and "db_link" in col:
            cidx = col["db_link"] + 1
            cell = ws.cell(row=r_idx, column=cidx)
            if cell and cell.hyperlink and cell.hyperlink.target:
                if "kaggle.com" in cell.hyperlink.target.lower():
                    url = cell.hyperlink.target.strip()

        # Last-chance fallback: scan entire row text for Kaggle URL.
        if not url:
            joined = " ".join(str(x) for x in row if x is not None)
            m = re.search(r"https?://(?:www\.)?kaggle\.com/datasets/[^\s]+", joined, flags=re.IGNORECASE)
            if m:
                url = m.group(0).strip()

        topics.append({
            "category": category,
            "topic": topic,
            "objective": objective,
            "tags": tags,
            "db_link": url
        })

    print(f"Loaded {len(topics)} topics from {filepath}")
    return topics


# ══════════════════════════════════════════════════════════════
# KAGGLE DOWNLOADER
# ══════════════════════════════════════════════════════════════

def extract_slug(url: str) -> str | None:
    m = re.search(r"kaggle\.com/datasets/([^/\s?#]+/[^/\s?#]+)", url.strip(), flags=re.IGNORECASE)
    return m.group(1) if m else None


def parse_huggingface_dataset_id(url_or_id: str) -> str | None:
    raw = url_or_id.strip()
    m = re.search(r"huggingface\.co/datasets/([^/\s?#]+/[^/\s?#]+)", raw, flags=re.IGNORECASE)
    if m:
        return m.group(1)
    if not raw.lower().startswith(("http://", "https://")) and raw:
        return raw.strip("/")
    return None


def download_dataset(slug: str) -> str | None:
    try:
        import kagglehub
        print(f"  Downloading: {slug}")
        path = kagglehub.dataset_download(slug)
        print(f"  ✓ {path}")
        return path
    except Exception as e:
        print(f"  ✗ Download failed: {e}")
        return None


def download_huggingface_dataset(dataset_id: str) -> str | None:
    try:
        from huggingface_hub import snapshot_download
        print(f"  Downloading Hugging Face dataset: {dataset_id}")
        path = snapshot_download(repo_id=dataset_id, repo_type="dataset")
        print(f"  ✓ {path}")
        return path
    except Exception as e:
        print(f"  ✗ Hugging Face download failed: {e}")
        return None


def _extract_archive(filepath: str, outdir: str) -> str | None:
    try:
        lower = filepath.lower()
        if zipfile.is_zipfile(filepath):
            with zipfile.ZipFile(filepath) as zf:
                zf.extractall(outdir)
            return outdir
        if tarfile.is_tarfile(filepath):
            with tarfile.open(filepath) as tf:
                tf.extractall(outdir)
            return outdir
        if lower.endswith(".gz") and not lower.endswith(".tar.gz"):
            target = Path(outdir) / Path(filepath).with_suffix("").name
            import gzip
            with gzip.open(filepath, "rb") as src, open(target, "wb") as dst:
                shutil.copyfileobj(src, dst)
            return outdir
    except Exception:
        return None
    return None


def download_dataset_from_url(url: str, dataset_id: str = "") -> str | None:
    try:
        parsed = urlparse(url)
        name = dataset_id or Path(parsed.path).name or "downloaded_dataset"
        base = Path("/tmp") / "storybit_external_datasets" / hashlib.md5(url.encode()).hexdigest()
        base.mkdir(parents=True, exist_ok=True)
        target = base / (name if "." in name else "dataset_download")

        print(f"  Downloading URL dataset: {url}")
        with httpx.stream("GET", url, follow_redirects=True, timeout=300) as r:
            r.raise_for_status()
            with open(target, "wb") as f:
                for chunk in r.iter_bytes():
                    if chunk:
                        f.write(chunk)

        extracted = _extract_archive(str(target), str(base / "extracted"))
        final_path = extracted or str(base)
        print(f"  ✓ {final_path}")
        return final_path
    except Exception as e:
        print(f"  ✗ URL download failed: {e}")
        return None


# ══════════════════════════════════════════════════════════════
# FILE LOADER
# ══════════════════════════════════════════════════════════════

def find_data_files(dataset_path: str) -> list[str]:
    path  = Path(dataset_path)
    files = []
    for ext in ["*.csv", "*.json", "*.jsonl", "*.ndjson", "*.tsv",
                "*.parquet", "*.xlsx", "*.xls", "*.txt", "*.md", "*.log",
                "*.xml"]:
        files.extend(glob.glob(str(path / "**" / ext), recursive=True))
    files = [f for f in files if os.path.getsize(f) < 500 * 1024 * 1024]
    files.sort(key=lambda f: os.path.getsize(f), reverse=True)
    return files


def find_media_files(dataset_path: str) -> list[str]:
    path = Path(dataset_path)
    media_exts = [
        "*.jpg", "*.jpeg", "*.png", "*.webp", "*.gif", "*.bmp", "*.tif", "*.tiff",
        "*.mp3", "*.wav", "*.flac", "*.m4a", "*.ogg",
        "*.mp4", "*.mov", "*.mkv", "*.avi", "*.webm",
    ]
    files = []
    for ext in media_exts:
        files.extend(glob.glob(str(path / "**" / ext), recursive=True))
    files = [f for f in files if os.path.getsize(f) < 500 * 1024 * 1024]
    files.sort(key=lambda f: os.path.getsize(f), reverse=True)
    return files


def load_dataframe(filepath: str) -> pd.DataFrame | None:
    ext = Path(filepath).suffix.lower()
    try:
        if ext in (".csv", ".tsv"):
            sep = "\t" if ext == ".tsv" else ","
            for enc in ["utf-8", "utf-8-sig", "latin-1", "cp1252"]:
                try:
                    df = pd.read_csv(filepath, sep=sep, encoding=enc,
                                     on_bad_lines="skip", low_memory=False)
                    if not df.empty:
                        return df
                except UnicodeDecodeError:
                    continue

        elif ext == ".json":
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                raw = json.load(f)
            if isinstance(raw, list):
                return pd.DataFrame(raw)
            if isinstance(raw, dict):
                for key in ["data", "items", "records", "results", "articles", "rows"]:
                    if key in raw and isinstance(raw[key], list):
                        return pd.DataFrame(raw[key])
                return pd.DataFrame([raw])

        elif ext in (".jsonl", ".ndjson"):
            records = []
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    line = line.strip()
                    if line:
                        try:
                            records.append(json.loads(line))
                        except json.JSONDecodeError:
                            continue
            return pd.DataFrame(records) if records else None

        elif ext == ".parquet":
            return pd.read_parquet(filepath)

        elif ext in (".xlsx", ".xls"):
            # first sheet is enough for ingestion; very large workbooks are trimmed later
            return pd.read_excel(filepath)

        elif ext in (".txt", ".md", ".log"):
            lines = []
            line_cap = _runtime_max_rows_per_ds if _runtime_max_rows_per_ds > 0 else float("inf")
            with open(filepath, "r", encoding="utf-8", errors="replace") as f:
                for line in f:
                    v = line.strip()
                    if v:
                        lines.append(v)
                        if len(lines) >= line_cap:
                            break
            return pd.DataFrame({"text": lines}) if lines else None

        elif ext == ".xml":
            try:
                df = pd.read_xml(filepath)
                if df is not None and not df.empty:
                    return df
            except Exception:
                return None

    except Exception as e:
        print(f"      Load error: {e}")
    return None


# ══════════════════════════════════════════════════════════════
# LM STUDIO SCHEMA ANALYSER
# ══════════════════════════════════════════════════════════════

_schema_cache: dict[str, dict] = {}

_ALWAYS_NOISE = {
    "id", "post_id", "comment_id", "tweet_id", "user_id", "uuid",
    "identifier", "record_id", "row_id",
    "author", "username", "user_name", "screen_name", "handle",
    "url", "link", "href", "permalink",
    "score", "votes", "upvote_ratio", "downvote_ratio", "num_comments",
    "followers", "friends", "favourites", "likes", "ups", "downs",
    "gilded", "distinguished", "stickied", "is_self", "over_18",
    "spoiler", "locked", "user_verified", "user_location",
    "retrieved_at", "inserted_at", "loaded_at", "ingested_at",
    "unnamed: 0", "row-cell", "row cell", "s.no", "s_no", "logid",
}
_NOISE_SUBS = ("_id", "_url", "_link", "ratio", "_count", "_votes", "identifier", "unnamed")

_DATE_NAMES = {
    "date", "created_at", "created_utc", "published_at", "publish_date",
    "timestamp", "post_date", "article_date", "news_date", "time",
    "created", "updated_at", "pub_date", "publication_date", "datetime",
}

_BODY_NAMES = {
    "body", "text", "selftext", "content", "description", "summary",
    "abstract", "review", "comment", "post", "transcript", "answer",
    "response", "message", "article", "paragraph", "details",
}


def _is_noise(col: str) -> bool:
    cl = col.lower()
    if cl in _ALWAYS_NOISE:
        return True
    return any(sub in cl for sub in _NOISE_SUBS)


def _safe_avg_words(series: pd.Series, n: int = 300) -> float:
    try:
        clean = series.dropna().astype(str).str.strip()
        clean = clean[~clean.str.lower().isin(
            {"", "nan", "none", "null", "n/a", "[removed]", "[deleted]"})]
        return clean.head(n).apply(lambda x: len(x.split())).mean() if not clean.empty else 0.0
    except Exception:
        return 0.0


def _is_identifier_like(series: pd.Series, sample_n: int = 400) -> bool:
    """Heuristic: mostly-unique alphanumeric tokens with little language signal."""
    try:
        s = series.dropna().astype(str).str.strip()
        s = s[~s.str.lower().isin({"", "nan", "none", "null"})].head(sample_n)
        if s.empty:
            return False
        uniq_ratio = s.nunique() / max(len(s), 1)
        avg_words = s.apply(lambda x: len(x.split())).mean()
        alpha_num_ratio = s.apply(
            lambda x: bool(re.search(r"[a-zA-Z]", x)) and bool(re.search(r"\d", x))
        ).mean()
        long_token_ratio = s.apply(lambda x: len(x) >= 8 and " " not in x).mean()
        return uniq_ratio >= 0.9 and avg_words <= 2 and (alpha_num_ratio >= 0.5 or long_token_ratio >= 0.7)
    except Exception:
        return False


def _is_ingestion_col(col: str) -> bool:
    cl = col.lower()
    return any(t in cl for t in ("retrieved", "inserted", "loaded", "ingested", "etl"))


def _is_bad_col_name(col: str) -> bool:
    cl = col.lower().strip()
    return (
        cl.startswith("unnamed")
        or cl in {"row-cell", "row cell", "s.no", "s_no", "logid", "id", "no.", "no"}
        or cl.endswith("_id")
    )


def _find_date_col(df: pd.DataFrame) -> str:
    for col in df.columns:
        if col.lower() in _DATE_NAMES:
            return col
    for col in df.columns:
        cl = col.lower()
        if "date" in cl or "publish" in cl or ("time" in cl and "sentiment" not in cl):
            return col
    return ""


def _fallback_sentence_cols(df: pd.DataFrame, date_col: str = "", limit: int = 3) -> list[str]:
    """Pick best-effort columns when LLM/stats produce no primary text fields."""
    scored: list[tuple[float, str]] = []
    for col in df.columns:
        if col == date_col or _is_noise(col) or _is_ingestion_col(col) or _is_bad_col_name(col):
            continue
        s = df[col]
        non_null = s.dropna()
        if non_null.empty:
            continue
        first = non_null.iloc[0]
        if isinstance(first, (list, dict)):
            continue

        score = 0.0
        cl = col.lower()
        if s.dtype in [object, "string"]:
            score += 3.0
            aw = _safe_avg_words(s)
            if 1 <= aw <= 12:
                score += 1.0
        else:
            score += 1.5

        if any(k in cl for k in ("name", "title", "movie", "state", "city", "country", "party", "category", "type")):
            score += 2.0
        if any(k in cl for k in ("gross", "revenue", "amount", "price", "count", "total", "rate", "percent", "score")):
            score += 1.5
        if _is_identifier_like(s):
            score -= 4.0

        try:
            uniq_ratio = non_null.nunique() / max(len(non_null), 1)
            if 0.02 <= uniq_ratio <= 0.98:
                score += 0.75
        except Exception:
            pass

        scored.append((score, col))

    scored.sort(key=lambda x: x[0], reverse=True)
    return [c for _, c in scored[:limit]]


def _build_content_cols(df: pd.DataFrame, primary: list[str], context: list[str],
                        date_col: str = "", row_source_url_col: str = "") -> list[str]:
    # Keep every available dataset column in row content so we do not lose context.
    # The only excluded column is a detected per-row source URL because that is
    # stored separately in source_url.
    cols = []
    blocked = {row_source_url_col}
    for col in df.columns:
        if col in blocked:
            continue
        if col not in df.columns:
            continue
        cols.append(col)
    return cols


def _lm_running() -> tuple[bool, str]:
    try:
        r    = httpx.get(_LM_MODELS, timeout=5)
        data = r.json()
        mid  = ""
        def _find(obj, d=0):
            nonlocal mid
            if d > 4 or mid:
                return
            if isinstance(obj, dict):
                for field in ["id", "model_id", "modelId"]:
                    v = obj.get(field, "")
                    if isinstance(v, str) and len(v) > 5:
                        mid = v; return
                for val in obj.values():
                    _find(val, d + 1)
            elif isinstance(obj, list):
                for item in obj:
                    _find(item, d + 1)
        _find(data)
        if not mid:
            mid = "lfm2.5-1.2b-instruct-thinking-claude-high-reasoning-mlx"
        return True, mid
    except Exception:
        return False, ""


# ══════════════════════════════════════════════════════════════
# DATASET METADATA GENERATOR
# ══════════════════════════════════════════════════════════════

_metadata_cache: dict[str, dict] = {}

_META_SYSTEM = """Classify a Kaggle dataset. Return ONLY valid JSON matching the required schema.
Rules: category=broad domain (Politics|Technology|Science|Health|Business|Sports|Entertainment|Education|Society|Environment), topic=specific 3-6 words, tags=3-6 keywords, objective in {News, Analysis, Learning, Curiosity, Self improvement, Entertainment}."""


def generate_dataset_metadata(df: pd.DataFrame, slug: str, hint_objective: str = "") -> dict:
    if slug in _metadata_cache:
        return _metadata_cache[slug]

    dataset_name = slug.split("/")[-1]

    def _fallback(reason: str = "") -> dict:
        if reason:
            print(f"      [meta] {reason} — using slug-derived fallback")
        return {
            "category": "General",
            "topic":    dataset_name.replace("-", " ").title(),
            "tags":     [w for w in dataset_name.split("-") if len(w) > 2][:4] or ["dataset"],
            "objective": hint_objective or "Learning",
        }

    ok, model_id = _lm_running()
    if not ok:
        meta = _fallback("LM Studio offline")
        _metadata_cache[slug] = meta
        return meta

    cols = list(df.columns)[:20]

    text_cols = [
        c for c in cols
        if df[c].dtype in [object, "string"]
        and not any(sub in c.lower() for sub in ("_id", "_url", "id", "link", "score"))
    ][:6]

    sample_rows = []
    for ri in [0, len(df)//2, len(df)-1]:
        if ri >= len(df):
            continue
        row   = df.iloc[ri]
        cells = []
        for c in text_cols:
            try:
                v = str(row[c]).strip()
                if v.lower() not in ("nan", "none", "null", ""):
                    cells.append(f"{c}={v[:40]}")
            except Exception:
                continue
        if cells:
            sample_rows.append(" | ".join(cells[:4]))

    prompt = (
        f"Dataset: {slug}\n"
        f"Columns: {cols}\n"
        f"Sample rows:\n" + "\n".join(sample_rows[:3]) +
        "\n\nClassify this dataset."
    )

    if len(_META_SYSTEM) + len(prompt) > 3000:
        prompt = prompt[:2800 - len(_META_SYSTEM)]

    try:
        r = httpx.post(
            _LM_CHAT_URL,
            json={
                "model":           model_id,
                "messages": [
                    {"role": "system", "content": _META_SYSTEM},
                    {"role": "user",   "content": prompt},
                ],
                "temperature":     0.15,
                "max_tokens":      180,
                "stream":          False,
                "response_format": _METADATA_JSON_SCHEMA,
            },
            timeout=90,
        )

        if r.status_code != 200:
            meta = _fallback(f"LM Studio HTTP {r.status_code}")
            _metadata_cache[slug] = meta
            return meta

        raw = r.json()["choices"][0]["message"]["content"].strip()
        raw = re.sub(r"<think>.*?</think>", "", raw, flags=re.DOTALL).strip()
        raw = re.sub(r"^```(?:json)?\s*", "", raw)
        raw = re.sub(r"\s*```$", "", raw).strip()

        m = re.search(r"\{.*\}", raw, re.DOTALL)
        if not m:
            meta = _fallback("No JSON in response")
            _metadata_cache[slug] = meta
            return meta

        meta = json.loads(m.group())
        meta.setdefault("category", "General")
        meta.setdefault("topic",    dataset_name.replace("-", " ").title())
        meta.setdefault("tags",     [dataset_name])
        meta.setdefault("objective", hint_objective or "Learning")

        if not isinstance(meta["tags"], list):
            meta["tags"] = [str(meta["tags"])]
        meta["tags"] = [str(t).strip() for t in meta["tags"] if str(t).strip()][:6]
        meta["objective"] = str(meta.get("objective", hint_objective or "Learning")).strip() or (hint_objective or "Learning")

        print(f"      [meta] category: {meta['category']}")
        print(f"      [meta] topic:    {meta['topic']}")
        print(f"      [meta] tags:     {meta['tags']}")
        print(f"      [meta] objective:{meta['objective']}")

        _metadata_cache[slug] = meta
        return meta

    except json.JSONDecodeError as e:
        meta = _fallback(f"JSON parse error: {e}")
        _metadata_cache[slug] = meta
        return meta
    except Exception as e:
        meta = _fallback(f"Exception: {e}")
        _metadata_cache[slug] = meta
        return meta


_SCHEMA_SYSTEM = """Classify CSV columns for a RAG pipeline. Return ONLY valid JSON matching the required schema.

primary = rich text columns (avg_words>=8 OR named: body,text,selftext,content,description,summary,abstract,review,comment,post,transcript,answer,response)
context = short labels used as prefix (subreddit,category,title,country,source,platform)
noise   = IDs,URLs,usernames,timestamps,scores,numbers,booleans
date_col = column holding original publish date (created_at,created_utc,date,timestamp,published_at) or ""

Template examples:
  Reddit:  "{subreddit}: {title}. {body}"
  News:    "{source}: {title}. {summary}"
  Books:   "{title} by {authors}: {description}"
  Generic: "{context_col}: {primary_col}"
Only use primary+context cols in template. Never noise cols."""
_SCHEMA_SYSTEM += """
If no rich text columns exist, choose 1-3 most descriptive non-noise columns as primary
even if short, so each row can still become a meaningful sentence."""


def _build_schema_prompt(df: pd.DataFrame, detailed: bool = False) -> str:
    MAX_CHARS = 3600 if detailed else 2800

    rows = ["col|type|fill|uniq|avgW|sample_value"]
    for col in df.columns:
        s      = df[col]
        dtype  = str(s.dtype)[:6]
        fill   = f"{int(s.notna().mean() * 100)}%"
        first  = s.dropna().iloc[0] if s.notna().any() else None
        avg_w  = "-"
        sample = ""
        if s.dtype in [object, "string"] and not isinstance(first, (list, dict)):
            avg_w = f"{_safe_avg_words(s):.0f}"
            try:
                v = (s.dropna().astype(str).str.strip()
                      .replace(["nan","none","null",""], pd.NA)
                      .dropna().head(1).tolist())
                if v:
                    sample = v[0][:45].replace("|", " ").replace("\n", " ")
            except Exception:
                pass
        uniq = "-"
        try:
            non_null = s.dropna()
            if len(non_null) > 0:
                uniq = f"{(non_null.nunique() / len(non_null)):.2f}"
        except Exception:
            pass
        rows.append(f"{col}|{dtype}|{fill}|{uniq}|{avg_w}|{sample}")
    schema_block = "\n".join(rows)

    text_cols = [
        c for c in df.columns
        if df[c].dtype in [object, "string"]
        and not _is_noise(c)
        and not isinstance(
            df[c].dropna().iloc[0] if df[c].notna().any() else None,
            (list, dict)
        )
        and _safe_avg_words(df[c]) >= 3
    ][:5]

    sample_lines = []
    remaining = MAX_CHARS - len(schema_block) - 50
    if text_cols and remaining > 200:
        cell_lim = max(25, min(60, remaining // max(len(text_cols), 1) // 3))
        row_cap = 8 if detailed else 3
        for ri in range(0, min(len(df), 80), max(1, len(df) // row_cap))[:row_cap]:
            row   = df.iloc[ri]
            cells = []
            for c in text_cols:
                val = row.get(c, "")
                try:
                    if pd.isna(val): continue
                except (TypeError, ValueError):
                    pass
                v = str(val).strip()
                if v.lower() in ("nan","none","null","[removed]","[deleted]",""):
                    continue
                cells.append(f"{c}={v[:cell_lim]}")
            if cells:
                line = " | ".join(cells)
                if len(schema_block) + len("\n".join(sample_lines)) + len(line) < MAX_CHARS:
                    sample_lines.append(line)

    prompt = schema_block
    if sample_lines:
        prompt += "\n\nSAMPLE DATA ROWS:\n" + "\n".join(sample_lines)
    prompt += "\n\nNow classify the columns."

    return prompt[:MAX_CHARS]


def _call_schema_llm(df: pd.DataFrame, model_id: str, detailed: bool = False) -> dict | None:
    user_prompt = _build_schema_prompt(df, detailed=detailed)
    total_chars = len(_SCHEMA_SYSTEM) + len(user_prompt)
    print(f"      [LM Studio] Prompt {total_chars} chars (~{total_chars//4} tokens)")

    payload = {
        "model":           model_id,
        "messages": [
            {"role": "system", "content": _SCHEMA_SYSTEM},
            {"role": "user",   "content": user_prompt},
        ],
        "temperature":     0.05,
        "max_tokens":      400 if detailed else 250,
        "stream":          False,
        "response_format": _SCHEMA_JSON_SCHEMA,
    }

    try:
        r = httpx.post(_LM_CHAT_URL, json=payload, timeout=150)
        if r.status_code != 200:
            print(f"      [LM Studio] HTTP {r.status_code}: {r.text[:200]}")
            return None

        content = r.json()["choices"][0]["message"]["content"].strip()
        content = re.sub(r"<think>.*?</think>", "", content, flags=re.DOTALL).strip()
        content = re.sub(r"^```(?:json)?\s*", "", content)
        content = re.sub(r"\s*```$", "", content).strip()

        m = re.search(r"\{.*\}", content, re.DOTALL)
        if not m:
            print(f"      [LM Studio] No JSON found in response")
            return None

        result = json.loads(m.group())
        result.setdefault("confidence",        1.0)
        result.setdefault("reasoning",         "")
        result.setdefault("is_social",         False)
        result.setdefault("dataset_type",      "general")
        result.setdefault("sentence_template", "")
        result.setdefault("date_col",          "")
        return result

    except json.JSONDecodeError as e:
        print(f"      [LM Studio] JSON parse error: {e}")
        return None
    except Exception as e:
        print(f"      [LM Studio] Exception: {e}")
        return None


def _validate_schema(result: dict, df: pd.DataFrame) -> dict:
    valid   = set(df.columns)
    primary, context, noise = [], [], list(result.get("noise", []))

    for col in result.get("primary", []):
        if col not in valid:
            continue
        if _is_noise(col) or _is_ingestion_col(col) or _is_identifier_like(df[col]) or _is_bad_col_name(col):
            noise.append(col); continue
        if df[col].dtype in ["int64", "float64", "int32", "float32"]:
            context.append(col); continue
        avg_w = _safe_avg_words(df[col])
        if avg_w < 8 and col.lower() not in _BODY_NAMES:
            context.append(col)
        else:
            primary.append(col)

    for col in result.get("context", []):
        if col not in valid:
            continue
        if _is_noise(col) or _is_ingestion_col(col) or _is_identifier_like(df[col]) or _is_bad_col_name(col):
            noise.append(col); continue
        context.append(col)

    classified = set(primary + context + noise)
    for col in df.columns:
        if col in classified:
            continue
        if _is_noise(col) or _is_ingestion_col(col) or _is_identifier_like(df[col]) or _is_bad_col_name(col):
            noise.append(col)
        elif df[col].dtype in ["int64", "float64", "int32", "float32"]:
            context.append(col)
        else:
            avg_w = _safe_avg_words(df[col])
            if avg_w >= 8 or col.lower() in _BODY_NAMES:
                primary.append(col)
            elif avg_w >= 2:
                context.append(col)
            else:
                noise.append(col)

    tmpl    = result.get("sentence_template", "")
    allowed = set(primary + context)
    for raw_ref in re.findall(r"\{([^{}]+)\}", tmpl):
        ref = raw_ref.strip()
        if ref not in valid or ref not in allowed:
            tmpl = tmpl.replace(f"{{{raw_ref}}}", "")
        elif ref != raw_ref:
            tmpl = tmpl.replace(f"{{{raw_ref}}}", f"{{{ref}}}")
    tmpl = re.sub(r"\.\s*\.", ".", tmpl)
    tmpl = re.sub(r":\s*\.",  ".", tmpl)
    tmpl = re.sub(r"—\s*\.",  ".", tmpl)
    tmpl = re.sub(r"\s{2,}",  " ", tmpl).strip()
    tmpl = re.sub(r"[—:\s]+$","",  tmpl).strip()

    date_col = result.get("date_col", "")
    if date_col not in valid:
        date_col = _find_date_col(df)

    if date_col:
        primary = [c for c in primary if c != date_col]
        context = [c for c in context if c != date_col]
        noise.append(date_col) if date_col not in noise else None

    row_source_url_col = _find_row_source_url_col(df)
    if row_source_url_col:
        primary = [c for c in primary if c != row_source_url_col]
        context = [c for c in context if c != row_source_url_col]
        noise.append(row_source_url_col) if row_source_url_col not in noise else None

    # Structured/tabular datasets often have short text fields only.
    # If LLM/stat rules leave us without primary columns, promote a few
    # context columns so rows can still be converted into searchable text.
    if not primary:
        promoted = [c for c in context if c in set(_fallback_sentence_cols(df, date_col, limit=3))]
        if not promoted:
            promoted = _fallback_sentence_cols(df, date_col, limit=3)
        if promoted:
            primary.extend(promoted)
            context = [c for c in context if c not in set(promoted)]

    is_rich_text = any(_safe_avg_words(df[c]) >= 8 or c.lower() in _BODY_NAMES for c in primary)
    min_words = MIN_ROW_WORDS if is_rich_text else 2
    content_cols = _build_content_cols(df, primary, context, date_col, row_source_url_col)

    return {
        **result,
        "primary":           list(dict.fromkeys(primary)),
        "context":           list(dict.fromkeys(context)),
        "noise":             list(dict.fromkeys(noise)),
        "sentence_template": tmpl,
        "date_col":          date_col,
        "min_words":         min_words,
        "tabular_mode":      not is_rich_text,
        "row_source_url_col": row_source_url_col,
        "content_cols":      content_cols,
    }


def _stat_fallback(df: pd.DataFrame) -> dict:
    date_col = _find_date_col(df)
    row_source_url_col = _find_row_source_url_col(df)
    primary, context = [], []

    for col in df.columns:
        if _is_noise(col) or _is_ingestion_col(col) or _is_bad_col_name(col):
            continue
        if _is_identifier_like(df[col]):
            continue
        first = df[col].dropna().iloc[0] if df[col].notna().any() else None
        if isinstance(first, (list, dict)):
            continue
        if col == date_col or col == row_source_url_col:
            continue
        avg_w = _safe_avg_words(df[col])
        if avg_w >= 8 or col.lower() in _BODY_NAMES:
            primary.append(col)
        elif avg_w >= 1 or df[col].dtype in ["int64", "float64", "int32", "float32"]:
            context.append(col)

    ctx_clean = [c for c in context if c != date_col]
    tmpl = ""
    if primary:
        pfx  = f"{{{ctx_clean[0]}}}: " if ctx_clean else ""
        tmpl = pfx + ". ".join(f"{{{c}}}" for c in primary[:2])

    # Ensure at least one primary column for structured tables.
    if not primary:
        primary = _fallback_sentence_cols(df, date_col, limit=3)
        ctx_clean = [c for c in ctx_clean if c not in set(primary)]

    is_rich_text = any(_safe_avg_words(df[c]) >= 8 or c.lower() in _BODY_NAMES for c in primary)
    min_words = MIN_ROW_WORDS if is_rich_text else 2
    content_cols = _build_content_cols(df, primary[:3], ctx_clean[:], date_col, row_source_url_col)

    return {
        "primary":           primary[:3],
        "context":           ctx_clean[:2],
        "noise":             [],
        "date_col":          date_col,
        "is_social":         False,
        "dataset_type":      "general",
        "sentence_template": tmpl,
        "confidence":        0.5,
        "reasoning":         "stat fallback — LM Studio offline/failed",
        "used_llm":          False,
        "min_words":         min_words,
        "tabular_mode":      not is_rich_text,
        "row_source_url_col": row_source_url_col,
        "content_cols":      content_cols,
    }


def analyse_schema(df: pd.DataFrame) -> dict:
    key = hashlib.md5((str(list(df.columns)) + str(list(df.dtypes))).encode()).hexdigest()
    if key in _schema_cache:
        print(f"      [LM Studio] Using cached schema")
        return _schema_cache[key]

    running, model_id = _lm_running()
    if not running:
        print(f"      [LM Studio] Offline — using stats fallback")
        result = _stat_fallback(df)
        _schema_cache[key] = result
        return result

    print(f"      [LM Studio] Analysing with {model_id} (compact prompt)...")
    result = _call_schema_llm(df, model_id)

    if result is None:
        print(f"      [LM Studio] LLM failed — using stats fallback")
        result = _stat_fallback(df)
        result["used_llm"] = False
    else:
        result = _validate_schema(result, df)
        result["used_llm"] = True
        print(f"      type={result['dataset_type']}  "
              f"confidence={result['confidence']:.0%}  "
              f"date_col={result['date_col'] or 'none'}")
        print(f"      template: {result['sentence_template']}")
        print(f"      reasoning: {result['reasoning']}")
        print(f"      primary: {result['primary']}")
        print(f"      context: {result['context']}")

        primary_noisey = all(_is_identifier_like(df[c]) for c in result.get("primary", []) if c in df.columns) if result.get("primary") else True
        if result["confidence"] < 0.65 or primary_noisey:
            reason = "low confidence" if result["confidence"] < 0.65 else "weak primary columns"
            print(f"      {reason.title()} — retrying with detailed prompt...")
            r2 = _call_schema_llm(df, model_id, detailed=True)
            if r2 and r2.get("confidence", 0) > result["confidence"]:
                result = _validate_schema(r2, df)
                result["used_llm"] = True
                print(f"      Retry confidence: {result['confidence']:.0%}")

    _schema_cache[key] = result
    return result


# ══════════════════════════════════════════════════════════════
# ROW → SENTENCE
# ══════════════════════════════════════════════════════════════

_URL_RE  = re.compile(r"https?://\S+")
_HTML_RE = re.compile(r"<[^>]+>")
_WS_RE   = re.compile(r"\s+")
_BAD     = {"nan","none","null","n/a","na","","[]","{}","unknown",
            "[removed]","[deleted]","[ removed by moderator ]"}


def _looks_like_url(value: object) -> bool:
    if value is None:
        return False
    s = str(value).strip()
    return bool(re.match(r"^https?://", s, flags=re.IGNORECASE))


def _find_row_source_url_col(df: pd.DataFrame) -> str:
    preferred = ("url", "link", "permalink", "href", "article_url", "source_url", "web_url", "feed_url", "rss")
    secondary = ("source", "website", "domain", "feed")
    for names in (preferred, secondary):
        for col in df.columns:
            cl = str(col).lower().strip()
            if any(name == cl or name in cl for name in names):
                series = df[col].dropna().astype(str).str.strip().head(50)
                if not series.empty and series.apply(_looks_like_url).mean() >= 0.6:
                    return col
    for col in df.columns:
        series = df[col].dropna().astype(str).str.strip().head(50)
        if not series.empty and series.apply(_looks_like_url).mean() >= 0.9:
            return col
    return ""


def _clean(v: str, social: bool = False) -> str:
    v = _HTML_RE.sub(" ", str(v).strip())
    if social:
        v = _URL_RE.sub("", v)
    return _WS_RE.sub(" ", v).strip()


def _get(row: pd.Series, col: str, social: bool = False) -> str:
    val = row.get(col, "")
    if isinstance(val, (list, dict)):
        val = json.dumps(val)
    v = str(val).strip()
    return "" if v.lower() in _BAD else _clean(v, social)


def build_row_sentence(row: pd.Series, schema: dict) -> str:
    content_cols = schema.get("content_cols", [])
    social   = schema.get("is_social", False)
    min_words = int(schema.get("min_words", MIN_ROW_WORDS))

    # Always render the full row as labeled key-value content so every column
    # survives into the stored text, regardless of what schema selection picked.
    kv_cols = content_cols or list(row.index)
    kv = []
    for c in kv_cols:
        v = _get(row, c, social)
        if v:
            kv.append(f"{c}: {v}")

    result = " | ".join(kv).strip()
    return result if len(result.split()) >= min_words else ""


def chunk_content(text: str, chunk_words: int = CHUNK_WORDS, overlap: int = CHUNK_OVERLAP) -> list[str]:
    """Sentence-aware chunking toward 250-word target with overlap."""
    base = _clean(text)
    if not base:
        return []

    words = base.split()
    if len(words) <= chunk_words:
        return [base]

    chunks = []
    try:
        sentences = [s.strip() for s in sent_tokenize(base) if s.strip()]
    except Exception:
        sentences = []

    if sentences:
        cur, cur_words = [], 0
        for sent in sentences:
            sw = len(sent.split())
            if cur and cur_words + sw > chunk_words:
                chunk = " ".join(cur).strip()
                if chunk:
                    chunks.append(chunk)
                # overlap tail from previous chunk
                tail = []
                tail_words = 0
                for ps in reversed(cur):
                    pw = len(ps.split())
                    if tail_words + pw > overlap and tail:
                        break
                    tail.insert(0, ps)
                    tail_words += pw
                cur = tail[:]
                cur_words = sum(len(s.split()) for s in cur)
            cur.append(sent)
            cur_words += sw
        if cur:
            chunk = " ".join(cur).strip()
            if chunk:
                chunks.append(chunk)
    else:
        step = max(1, chunk_words - overlap)
        for i in range(0, len(words), step):
            chunk = " ".join(words[i:i + chunk_words]).strip()
            if chunk:
                chunks.append(chunk)

    return chunks


def _schema_acceptance_check(schema: dict, df: pd.DataFrame) -> tuple[bool, str]:
    primary = [c for c in schema.get("primary", []) if c in df.columns]
    content_cols = [c for c in schema.get("content_cols", []) if c in df.columns]
    if content_cols:
        return True, "ok"
    if not primary:
        return False, "no primary columns"
    if all(_is_bad_col_name(c) for c in primary):
        return False, "primary columns are weak placeholders"
    if all(_is_identifier_like(df[c]) for c in primary if c in df.columns):
        return False, "primary columns look identifier-like"
    return True, "ok"


def _record_failed_dataset(slug: str, reason: str, file: str = ""):
    entry = {"ts": time.strftime("%Y-%m-%dT%H:%M:%S"), "slug": slug, "file": file, "reason": reason}
    with open(FAILED_DATASETS_FILE, "a", encoding="utf-8") as f:
        f.write(json.dumps(entry, ensure_ascii=False) + "\n")


def _load_failed_slugs() -> list[str]:
    if not os.path.exists(FAILED_DATASETS_FILE):
        return []
    slugs = []
    with open(FAILED_DATASETS_FILE, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                obj = json.loads(line)
                slug = str(obj.get("slug", "")).strip()
                if slug:
                    slugs.append(slug)
            except Exception:
                continue
    seen = set()
    out = []
    for s in slugs:
        if s not in seen:
            seen.add(s)
            out.append(s)
    return out


def _load_retry_slugs_from_validation_report(report_path: str = "") -> list[str]:
    """Load dataset slugs with warn/error status from schema validation report JSON."""
    try:
        p = Path(report_path).expanduser() if report_path else None
        if p is None or not p.exists():
            candidates = sorted(Path("reports").glob("schema_validation_*.json"))
            if not candidates:
                return []
            p = candidates[-1]

        with open(p, "r", encoding="utf-8") as f:
            data = json.load(f)
        datasets = data.get("datasets", [])
        slugs = []
        for d in datasets:
            st = str(d.get("status", "")).lower()
            slug = str(d.get("dataset_slug", "")).strip()
            if slug and st in {"warn", "error"}:
                slugs.append(slug)
        # unique preserving order
        seen = set()
        out = []
        for s in slugs:
            if s not in seen:
                seen.add(s)
                out.append(s)
        return out
    except Exception:
        return []


# ══════════════════════════════════════════════════════════════
# SOURCE TYPE DETECTOR
# ══════════════════════════════════════════════════════════════

_SOURCE_RULES = [
    (["movie", "hollywood", "boxoffice", "imdb", "netflix",
      "streaming", "cinema", "tv-show"],                         "web_scrape"),
    (["news", "article", "headline", "bbc", "cnn", "reuters",
      "guardian", "nyt", "times", "press", "journal"],           "news"),
    (["book", "novel", "literature", "fiction", "goodreads"],    "book"),
    (["youtube", "video", "channel", "transcript"],              "youtube"),
    (["reddit", "subreddit", "tweet", "twitter", "x-com",
      "instagram", "tiktok", "facebook", "linkedin", "social"],  "web_scrape"),
    (["election", "vote", "ballot", "parliament", "congress"],   "news"),
    (["wikipedia", "wiki"],                                       "wikipedia"),
]
_src_cache: dict[str, str] = {}
_ALLOWED_SOURCE_TYPES = {"web_scrape", "news", "wikipedia", "book", "youtube"}


def detect_source_type(slug: str) -> str:
    if slug in _src_cache:
        return _src_cache[slug]
    name = slug.split("/")[-1].lower()
    for keywords, st in _SOURCE_RULES:
        if any(kw in name for kw in keywords):
            _src_cache[slug] = st
            return st
    # Quick LLM call — now with JSON schema for structured output
    try:
        ok, mid = _lm_running()
        if ok:
            r = httpx.post(_LM_CHAT_URL, json={
                "model": mid,
                "messages": [
                    {"role": "system",
                     "content": "Classify this Kaggle dataset name into a source type. "
                                "Return JSON with source_type set to ONE of: "
                                "web_scrape, news, wikipedia, book, youtube. "
                                "Use 'book' only when this is clearly a books/literature dataset."},
                    {"role": "user", "content": name},
                ],
                "max_tokens":      30,
                "temperature":     0,
                "response_format": _SOURCE_TYPE_JSON_SCHEMA,
            }, timeout=10)
            if r.status_code == 200:
                raw = r.json()["choices"][0]["message"]["content"].strip()
                try:
                    parsed = json.loads(raw)
                    word = parsed.get("source_type", "").strip().lower()
                except (json.JSONDecodeError, AttributeError):
                    word = raw.strip().lower().split()[0].strip(".,;:")
                if word in _ALLOWED_SOURCE_TYPES:
                    # Guard against over-predicting "book" on non-book slugs.
                    if word == "book" and not any(k in name for k in ("book", "novel", "author", "goodreads", "literature")):
                        word = "web_scrape"
                    _src_cache[slug] = word
                    return word
    except Exception:
        pass
    _src_cache[slug] = "web_scrape"
    return "web_scrape"


def build_source_context(
    source_id: str,
    provider: str = "kaggle",
    source_url: str = "",
    source_title: str = "",
) -> dict:
    dataset_name = source_title or source_id.split("/")[-1]
    provider_l = provider.lower().strip()
    provider_label = {
        "kaggle": "Kaggle",
        "huggingface": "HuggingFace",
        "url": "URL",
    }.get(provider_l, provider.title())

    if not source_url:
        if provider_l == "kaggle":
            source_url = f"https://www.kaggle.com/datasets/{source_id}"
        elif provider_l == "huggingface":
            source_url = f"https://huggingface.co/datasets/{source_id}"
        else:
            source_url = source_id

    source_key = f"{provider_l}_id"
    return {
        "provider": provider_l,
        "source_id": source_id,
        "source_key": source_key,
        "source_title": dataset_name,
        "source_url": source_url,
        "source_from": f"{provider_label}: {dataset_name}",
        "author_name": source_id.split("/")[0] if "/" in source_id else provider_label,
        "author_description": f"{provider_label} dataset: {source_id}",
        "source_type_name": dataset_name,
    }


# ══════════════════════════════════════════════════════════════
# DOCUMENT BUILDER  — one per CSV row
# ══════════════════════════════════════════════════════════════

def _make_doc(sentence: str, row: pd.Series, schema: dict,
              slug: str, fname: str, dataset_meta: dict,
              source_context: dict | None = None) -> dict:
    source_context = source_context or build_source_context(slug, provider="kaggle")
    dataset_name    = source_context.get("source_title", slug.split("/")[-1])
    source_from     = source_context.get("source_from", f"Kaggle: {dataset_name}")
    category        = dataset_meta.get("category", "General")
    topic           = dataset_meta.get("topic", dataset_name)
    tags            = dataset_meta.get("tags", [])
    objective       = dataset_meta.get("objective", "Learning")

    embedding_model = NOMIC_MODEL_ID if _use_nomic else GEMINI_MODEL

    published_at = None
    date_col     = schema.get("date_col", "")
    row_source_url = ""
    row_source_url_col = schema.get("row_source_url_col", "")
    if date_col and date_col in row.index:
        raw = row[date_col]
        try:
            is_na = pd.isna(raw)
        except (TypeError, ValueError):
            is_na = False
        if not is_na:
            v = str(raw).strip()
            if v and v.lower() not in ("", "nan", "none", "null"):
                published_at = v
    if row_source_url_col and row_source_url_col in row.index:
        raw_url = row[row_source_url_col]
        try:
            is_na_url = pd.isna(raw_url)
        except (TypeError, ValueError):
            is_na_url = False
        if not is_na_url:
            candidate = str(raw_url).strip()
            if _looks_like_url(candidate):
                row_source_url = candidate

    metadata: dict = {
        "category":        category,
        "topic":           topic,
        "tags":            tags,
        "objective":       objective,
        "source_from":     source_from,
        source_context.get("source_key", "kaggle_slug"): slug,
        "dataset_provider": source_context.get("provider", "kaggle"),
        "file":            fname,
        "embedding_model": embedding_model,
        "author": {
            "has_credentials": True,
            "name":            source_context.get("author_name", "dataset"),
            "description":     source_context.get("author_description", f"Dataset: {slug}"),
        },
    }
    if source_context.get("source_key") != "kaggle_slug":
        metadata["kaggle_slug"] = None
    if published_at:
        metadata["published_at"] = published_at
    if row_source_url:
        metadata["source_row_url"] = row_source_url

    return {
        "content":      sentence,
        "source_title": dataset_name,
        "source_url":   row_source_url or source_context.get("source_url", f"https://www.kaggle.com/datasets/{slug}"),
        "source_type":  detect_source_type(source_context.get("source_type_name", slug)),
        "metadata":     metadata,
    }


def _make_media_manifest_docs(media_files: list[str], slug: str, dataset_meta: dict,
                              source_context: dict | None = None) -> list[dict]:
    docs = []
    cap = _runtime_max_rows_per_ds if _runtime_max_rows_per_ds > 0 else len(media_files)
    for fp in media_files[:cap]:
        p = Path(fp)
        ext = p.suffix.lower().lstrip(".")
        size = os.path.getsize(fp)
        size_mb = round(size / (1024 * 1024), 3)
        content = f"Media asset file: {p.name}. Type: {ext}. SizeMB: {size_mb}."
        row = pd.Series({})
        schema = {"date_col": "", "is_social": False}
        doc = _make_doc(content, row, schema, slug, p.name, dataset_meta, source_context=source_context)
        md = doc.get("metadata", {})
        md["ingest_mode"] = "media_manifest"
        md["media_ext"] = ext
        md["media_size_mb"] = size_mb
        doc["metadata"] = md
        docs.append(doc)
    return docs


# ══════════════════════════════════════════════════════════════
# DATASET PROCESSOR
# ══════════════════════════════════════════════════════════════

def process_dataset(dataset_path: str, slug: str,
                    hint_category: str = "", hint_topic: str = "", hint_objective: str = "",
                    hint_tags: list[str] | None = None,
                    source_context: dict | None = None) -> list[dict]:
    source_context = source_context or build_source_context(slug, provider="kaggle")
    files = find_data_files(dataset_path)
    if not files:
        print(f"    No structured data files found. Trying media manifest fallback...")
        media_files = find_media_files(dataset_path)
        if not media_files:
            print(f"    No media files found either.")
            _record_failed_dataset(slug, "no supported files found")
            return []
        dataset_meta = {
            "category": hint_category or "General",
            "topic": hint_topic or slug.split("/")[-1].replace("-", " ").title(),
            "tags": hint_tags or [slug.split("/")[-1]],
            "objective": hint_objective or "Learning",
        }
        docs = _make_media_manifest_docs(media_files, slug, dataset_meta, source_context=source_context)
        print(f"    Media fallback created {len(docs)} docs from {len(media_files)} files")
        return docs

    print(f"    Files: {[Path(f).name for f in files]}")

    all_docs     = []
    seen_hashes  = set()
    total_rows   = 0
    dataset_meta = None

    for filepath in files:
        if _runtime_max_rows_per_ds > 0 and total_rows >= _runtime_max_rows_per_ds:
            break

        fname   = Path(filepath).name
        size_mb = os.path.getsize(filepath) / (1024 * 1024)
        print(f"\n    ── {fname}  ({size_mb:.1f} MB)")

        df = load_dataframe(filepath)
        if df is None or df.empty:
            print(f"      Empty or unreadable — skipping")
            continue

        if _runtime_max_rows_per_ds > 0:
            rows_left = _runtime_max_rows_per_ds - total_rows
            df = df.head(rows_left)
        print(f"      Shape: {df.shape[0]:,} rows × {df.shape[1]} cols")

        if dataset_meta is None:
            print(f"      Generating dataset metadata (LLM)...")
            dataset_meta = generate_dataset_metadata(df, slug, hint_objective=hint_objective)
            if hint_category and dataset_meta.get("category") in ("", "General"):
                dataset_meta["category"] = hint_category
            if hint_topic and dataset_meta.get("topic", "").lower() in ("", "general"):
                dataset_meta["topic"] = hint_topic
            if hint_objective and dataset_meta.get("objective", "").strip() == "":
                dataset_meta["objective"] = hint_objective
            if hint_tags:
                existing = set(dataset_meta.get("tags", []))
                dataset_meta["tags"] = list(existing | set(hint_tags))[:6]

        try:
            schema = analyse_schema(df)
        except Exception as e:
            print(f"      Schema analysis failed: {e} — using stats fallback")
            schema = _stat_fallback(df)
        primary = schema.get("primary", [])
        content_cols = schema.get("content_cols", [])

        if not primary and not content_cols:
            print(f"      ✗ No usable columns found — skipping file")
            _record_failed_dataset(slug, "no usable columns", fname)
            continue

        accepted, why = _schema_acceptance_check(schema, df)
        if not accepted:
            print(f"      ✗ Schema quality check failed ({why}) — skipping file")
            _record_failed_dataset(slug, f"schema_rejected: {why}", fname)
            continue

        added = skipped_empty = skipped_dup = 0

        for _, row in df.iterrows():
            try:
                sentence = build_row_sentence(row, schema)
                if not sentence:
                    skipped_empty += 1
                    continue

                chunks = chunk_content(sentence, CHUNK_WORDS, CHUNK_OVERLAP)
                if not chunks:
                    skipped_empty += 1
                    continue

                for chunk in chunks:
                    h = hashlib.md5(chunk.encode()).hexdigest()
                    if h in seen_hashes:
                        skipped_dup += 1
                        continue
                    seen_hashes.add(h)

                    all_docs.append(_make_doc(chunk, row, schema, slug, fname, dataset_meta, source_context=source_context))
                    added += 1
            except Exception:
                skipped_empty += 1

        total_rows += len(df)
        print(f"      → {added:,} rows  "
              f"(skipped: {skipped_empty} empty, {skipped_dup} dup)")

    print(f"\n    Total docs: {len(all_docs):,}")
    return all_docs


# ══════════════════════════════════════════════════════════════
# EMBEDDING  — Gemini primary, nomic fallback
# ══════════════════════════════════════════════════════════════

class DailyQuotaError(Exception):
    pass


def _parse_retry_delay(err: str) -> float:
    m = re.search(r"retryDelay['\"]?\s*:\s*['\"]([\d.]+)s", err)
    if m: return float(m.group(1)) + 2
    m = re.search(r"retry in ([\d.]+)s", err, re.IGNORECASE)
    if m: return float(m.group(1)) + 2
    return 65.0


def _embed_gemini(contents: list[str], gemini_client) -> list:
    for attempt in range(5):
        try:
            resp = gemini_client.models.embed_content(
                model=GEMINI_MODEL,
                contents=contents,
                config=genai_types.EmbedContentConfig(
                    task_type="RETRIEVAL_DOCUMENT",
                    output_dimensionality=768,
                ),
            )
            return [list(e.values) for e in resp.embeddings]
        except Exception as e:
            err = str(e)
            if "PerDay" in err or "EmbedContentRequestsPerDayPerUser" in err:
                raise DailyQuotaError(err)
            if ("429" in err or "RESOURCE_EXHAUSTED" in err) and attempt < 4:
                time.sleep(_parse_retry_delay(err))
            elif attempt < 4:
                time.sleep(5 * (attempt + 1))
            else:
                return []
    return []


def _embed_nomic(contents: list[str]) -> list:
    prefixed = [NOMIC_PREFIX + c for c in contents]
    all_emb  = []
    for i in range(0, len(prefixed), NOMIC_BATCH_SIZE):
        batch = prefixed[i:i + NOMIC_BATCH_SIZE]
        try:
            r = httpx.post(NOMIC_EMBED_ENDPOINT,
                           json={"model": NOMIC_MODEL_ID, "input": batch},
                           timeout=120)
            if r.status_code != 200:
                print(f"    [nomic] HTTP {r.status_code}")
                return []
            items = sorted(r.json()["data"], key=lambda x: x["index"])
            all_emb.extend(item["embedding"] for item in items)
        except Exception as e:
            print(f"    [nomic] Failed: {e}")
            return []
    return all_emb


def _verify_nomic() -> bool:
    try:
        r = httpx.post(NOMIC_EMBED_ENDPOINT,
                       json={"model": NOMIC_MODEL_ID, "input": ["test"]},
                       timeout=15)
        return r.status_code == 200
    except Exception:
        return False


def _is_timeout_error(err: Exception) -> bool:
    s = str(err).lower()
    return "statement timeout" in s or "canceling statement due to statement timeout" in s or "57014" in s


def _safe_trunc(s: str, lim: int = MAX_CONTENT_CHARS) -> str:
    s = _clean(s)
    return s if len(s) <= lim else s[:lim].rsplit(" ", 1)[0].strip()


def _validate_doc_contract(doc: dict) -> tuple[bool, str]:
    required_top = ["content", "source_title", "source_type", "metadata"]
    for k in required_top:
        if k not in doc:
            return False, f"missing field: {k}"
    if not isinstance(doc.get("metadata"), dict):
        return False, "metadata must be an object"
    if str(doc.get("source_type", "")).lower() not in _ALLOWED_SOURCE_TYPES:
        return False, "invalid source_type"
    content = str(doc.get("content", "")).strip()
    if not content:
        return False, "empty content"
    md = doc["metadata"]
    for k in ["category", "topic", "tags", "objective", "kaggle_slug", "file", "embedding_model"]:
        if k not in md:
            return False, f"missing metadata field: {k}"
    if not isinstance(md.get("tags"), list):
        return False, "metadata.tags must be an array"
    return True, "ok"


def _sanitize_for_insert(rows: list[dict]) -> list[dict]:
    clean_rows = []
    for r in rows:
        ok, reason = _validate_doc_contract(r)
        if not ok:
            _write_failed_rows([r], f"contract_validation_failed: {reason}")
            continue
        content = _safe_trunc(str(r.get("content", "")))
        if not content:
            continue
        metadata = r.get("metadata", {})
        if not isinstance(metadata, dict):
            metadata = {}
        source_type = str(r.get("source_type", "web_scrape")).strip().lower()
        if source_type not in _ALLOWED_SOURCE_TYPES:
            source_type = "web_scrape"
        clean_rows.append({
            **r,
            "content": content,
            "metadata": metadata,
            "source_type": source_type,
        })
    return clean_rows


def _write_failed_rows(rows: list[dict], reason: str):
    ts = time.strftime("%Y-%m-%dT%H:%M:%S")
    with open(FAILED_ROWS_FILE, "a", encoding="utf-8") as f:
        for r in rows:
            payload = {"ts": ts, "reason": reason, "row": r}
            f.write(json.dumps(payload, ensure_ascii=False) + "\n")


def _insert_rows_resilient(rows: list[dict], supabase: Client, depth: int = 0) -> bool:
    if not rows:
        return True
    try:
        supabase.table("documents").insert(rows).execute()
        return True
    except Exception as e:
        if _is_timeout_error(e) and len(rows) > 1:
            mid = max(1, len(rows) // 2)
            left, right = rows[:mid], rows[mid:]
            print(f"    Insert timeout at {len(rows)} rows — retrying split {len(left)} + {len(right)}")
            return _insert_rows_resilient(left, supabase, depth + 1) and _insert_rows_resilient(right, supabase, depth + 1)
        if len(rows) == 1:
            print(f"    ✗ Single-row insert failed — moved to {FAILED_ROWS_FILE}")
            _write_failed_rows(rows, str(e))
            return True
        print(f"    ✗ Insert failed ({len(rows)} rows): {e}")
        _write_failed_rows(rows, str(e))
        return False


def embed_and_insert(batch: list[dict], supabase: Client, gemini_client) -> bool:
    global _use_nomic
    batch = _sanitize_for_insert(batch)
    contents = [item["content"] for item in batch]
    if not contents:
        print(f"    ✗ Batch has no valid rows after sanitization")
        return False

    if _use_nomic:
        print(f"    [nomic] Embedding {len(batch)} rows...")
        embeddings = _embed_nomic(contents)
    else:
        print(f"    [Gemini] Embedding {len(batch)} rows...")
        try:
            embeddings = _embed_gemini(contents, gemini_client)
        except DailyQuotaError:
            print(f"\n  {'!'*50}")
            print(f"  Gemini daily quota hit — checking nomic fallback...")
            if not _verify_nomic():
                print(f"  ✗ nomic not loaded in LM Studio — aborting")
                return False
            print(f"  ✓ nomic available. AUTO-SWITCHING (permanent for this run)")
            print(f"  {'!'*50}\n")
            _use_nomic = True
            embeddings = _embed_nomic(contents)

    if not embeddings:
        print(f"    ✗ Embedding returned empty — skipping batch")
        return False

    if len(embeddings[0]) != 768:
        print(f"    ✗ Wrong dimension: {len(embeddings[0])} (expected 768)")
        return False

    rows = [{**item, "embedding": emb} for item, emb in zip(batch, embeddings)]

    try:
        print(f"    Inserting {len(rows)} rows...")
        ok = _insert_rows_resilient(rows, supabase)
        if not ok:
            return False
        print(f"    ✓ Inserted.")
        return True
    except Exception as e:
        print(f"    ✗ Insert failed: {e}")
        return False


# ══════════════════════════════════════════════════════════════
# PROGRESS LOG
# ══════════════════════════════════════════════════════════════

def load_progress() -> set[str]:
    if not os.path.exists(PROGRESS_FILE):
        return set()
    with open(PROGRESS_FILE) as f:
        return {line.strip() for line in f if line.strip()}


def mark_done(slug: str):
    with open(PROGRESS_FILE, "a") as f:
        f.write(slug + "\n")


# ══════════════════════════════════════════════════════════════
# FULL PIPELINE
# ══════════════════════════════════════════════════════════════

def run_full_pipeline(
    gemini_client,
    supabase: Client,
    retry_failed_only: bool = False,
    retry_report: str = "",
):
    topics  = read_spreadsheet(SPREADSHEET_FILE)
    done    = load_progress()
    batch   = []
    total   = 0
    skipped = 0

    failed_only = set(_load_failed_slugs()) if retry_failed_only else set()
    if retry_failed_only and not failed_only:
        fallback = _load_retry_slugs_from_validation_report(retry_report)
        failed_only = set(fallback)
    if retry_failed_only:
        print(f"Retry mode: {len(failed_only)} failed dataset(s) from {FAILED_DATASETS_FILE}")
        if retry_report:
            print(f"Retry report: {retry_report}")
        elif failed_only:
            print(f"Retry source: failed_datasets.log or latest reports/schema_validation_*.json")
    print(f"Topics: {len(topics)} | Done: {len(done)} | Remaining: {len(topics)-len(done)}\n")

    for idx, row in enumerate(topics, 1):
        category = row["category"]
        topic    = row["topic"]
        objective = row.get("objective", "")
        tags     = row["tags"]
        db_link  = row["db_link"]

        print(f"\n{'='*60}")
        print(f"[{idx:02d}/{len(topics)}] {category} → '{topic}'")

        if not db_link:
            print(f"  ⚠  No Kaggle link — skipping")
            skipped += 1; continue

        slug = extract_slug(db_link)
        if not slug:
            print(f"  ✗ Cannot parse slug from: {db_link}")
            skipped += 1; continue

        if retry_failed_only and slug not in failed_only:
            print(f"  ↷ Not in failed list — skipping")
            continue

        if slug in done and not retry_failed_only:
            print(f"  ✓ Already ingested"); continue

        path = download_dataset(slug)
        if not path:
            skipped += 1; continue

        docs = process_dataset(path, slug,
                               hint_category=category,
                               hint_topic=topic,
                               hint_objective=objective,
                               hint_tags=tags)
        if not docs:
            print(f"  ✗ No content extracted")
            mark_done(slug); skipped += 1; continue

        ds_rows = 0
        for doc in docs:
            batch.append(doc)
            ds_rows += 1
            if len(batch) >= BATCH_SIZE:
                ok = embed_and_insert(batch, supabase, gemini_client)
                if not ok:
                    print("  ⚠ Batch failed — logged to failed_rows.ndjson, continuing")
                    batch = []
                    continue
                total += len(batch)
                batch  = []
                if not _use_nomic:
                    print(f"    Waiting 62s (Gemini per-minute rate limit)...")
                    time.sleep(62)

        print(f"  → {ds_rows:,} rows queued")
        mark_done(slug)

    if batch:
        print(f"\nFlushing final {len(batch)} rows...")
        ok = embed_and_insert(batch, supabase, gemini_client)
        if ok:
            total += len(batch)

    print(f"\n{'='*60}")
    print(f"Done!  Rows inserted: {total:,}  |  Datasets skipped: {skipped}")
    print(f"{'='*60}")


# ══════════════════════════════════════════════════════════════
# TEST MODE
# ══════════════════════════════════════════════════════════════

def run_test_mode(args, gemini_client, supabase):
    slug    = args.slug
    dry_run = args.dry_run
    limit   = args.limit

    hint_topic    = args.topic    if args.topic    != "auto" else ""
    hint_category = args.category if args.category != "auto" else ""
    hint_objective = args.objective if args.objective != "auto" else ""
    hint_tags     = [t.strip() for t in args.tags.split(",") if t.strip()] if args.tags != "auto" else []

    W = 66
    print(f"\n{'═'*W}")
    print(f"  StoryBit — Single Dataset Test  (v6)")
    print(f"{'═'*W}")
    print(f"  Slug:     {slug}")
    print(f"  Dry run:  {dry_run}")
    print(f"  Limit:    {limit if limit > 0 else 'all rows'}")
    print(f"  Dataset rows cap: {_runtime_max_rows_per_ds if _runtime_max_rows_per_ds > 0 else 'no cap (full dataset)'}")
    if hint_category or hint_topic or hint_objective or hint_tags:
        print(f"  Hints:    category={hint_category!r}  topic={hint_topic!r}  objective={hint_objective!r}  tags={hint_tags}")
    print(f"  Note:     category/topic/tags auto-generated by LLM from data")
    print(f"{'═'*W}\n")

    print("── Step 1: Download ──────────────────────────────────")
    path = download_dataset(slug)
    if not path:
        sys.exit("✗ Download failed")

    print("\n── Step 2: LLM metadata generation + schema analysis ─")
    docs = process_dataset(path, slug,
                           hint_category=hint_category,
                           hint_topic=hint_topic,
                           hint_objective=hint_objective,
                           hint_tags=hint_tags)
    if not docs:
        sys.exit("✗ No rows extracted — check schema analysis output above")

    if limit > 0:
        docs = docs[:limit]
        print(f"\n  (limited to {limit} rows for this test)")

    print(f"\n── Step 3: Preview — exactly what Supabase will store ─")
    for i, doc in enumerate(docs[:3]):
        print(f"\n  ┌─ Row {i+1} {'─'*54}")
        def pr(label, val):
            print(f"  │  {label:<14} {str(val)[:80]}")
        m       = doc["metadata"]
        content = doc["content"]
        W2      = 74

        print(f"  │  {'COLUMN':<16} {'VALUE'}")
        print(f"  │  {'─'*16} {'─'*50}")
        def pr2(label, val, trunc=70):
            v = str(val)
            suffix = "…" if len(v) > trunc else ""
            print(f"  │  {label:<16} {v[:trunc]}{suffix}")
        pr2("content",      content, 80)
        pr2("source_title", doc["source_title"])
        pr2("source_url",   doc["source_url"], 72)
        pr2("source_type",  doc["source_type"])
        print(f"  │")
        print(f"  │  {'METADATA (JSONB)':<16}")
        print(f"  │  {'─'*16}")
        print(f"  │    category:       {m.get('category','')}")
        print(f"  │    topic:          {m.get('topic','')}")
        print(f"  │    tags:           {m.get('tags','')}")
        print(f"  │    objective:      {m.get('objective','')}")
        print(f"  │    source_from:    {m.get('source_from','')}")
        print(f"  │    file:           {m.get('file','')}")
        print(f"  │    kaggle_slug:    {m.get('kaggle_slug','')}")
        print(f"  │    embedding_model:{m.get('embedding_model','')}")
        pa = m.get("published_at")
        print(f"  │    published_at:   {pa if pa else '(no date column in this dataset)'}")
        a = m.get("author", {})
        print(f"  │    author.name:    {a.get('name','')}")
        print(f"  └{'─'*W2}")

    print(f"\n  Total rows to insert: {len(docs)}")

    if dry_run:
        print(f"\n── DRY RUN — nothing written to Supabase ─────────────")
        print(f"\n  When you run for real, verify with:")
        _print_sql(slug)
        return

    print(f"\n── Step 4: Embed + Insert → Supabase ─────────────────")
    ok = embed_and_insert(docs, supabase, gemini_client)
    if not ok:
        sys.exit("✗ Insert failed")

    print(f"\n── Done! {len(docs)} rows inserted.\n")
    _print_sql(slug)


def _print_sql(slug: str):
    print("  Supabase SQL to verify (using metadata JSONB since generated cols):")
    safe = slug.replace("'", "''")
    print(f"""
  -- View inserted rows
  SELECT id, content, source_type,
         metadata->>'category'        AS category,
         metadata->>'topic'           AS topic,
         metadata->>'objective'       AS objective,
         metadata->>'source_from'     AS source_from,
         metadata->>'embedding_model' AS embedding_model,
         metadata->>'published_at'    AS published_at,
         created_at
  FROM documents
  WHERE metadata->>'kaggle_slug' = '{safe}'
  ORDER BY created_at DESC LIMIT 20;

  -- Count by source_type
  SELECT source_type, COUNT(*) FROM documents GROUP BY source_type;

  -- Check embedding model distribution
  SELECT metadata->>'embedding_model' AS model, COUNT(*)
  FROM documents GROUP BY model;

  -- Check published_at coverage
  SELECT COUNT(*) FILTER (WHERE metadata->>'published_at' IS NOT NULL) AS with_date,
         COUNT(*) AS total
  FROM documents WHERE metadata->>'kaggle_slug' = '{safe}';

  -- Delete test rows for this dataset
  DELETE FROM documents WHERE metadata->>'kaggle_slug' = '{safe}';

  -- Full wipe (fresh start)
  TRUNCATE TABLE documents RESTART IDENTITY;
""")


# ══════════════════════════════════════════════════════════════
# ENTRY POINT
# ══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="StoryBit Kaggle ingestion — full pipeline + test mode")
    parser.add_argument("--test",     action="store_true",
                        help="Test mode: run on one dataset (does not touch progress log)")
    parser.add_argument("--slug",     default="umerhaddii/world-news-reddit-data-global-event-discussions",
                        help="[test] Kaggle dataset slug  e.g.  owner/dataset-name")
    parser.add_argument("--topic",    default="auto",
                        help="[test] Topic hint (default: auto-generated by LLM)")
    parser.add_argument("--category", default="auto",
                        help="[test] Category hint (default: auto-generated by LLM)")
    parser.add_argument("--objective", default="auto",
                        help="[test] Objective hint (default: auto-generated by LLM)")
    parser.add_argument("--tags",     default="auto",
                        help="[test] Comma-separated tag hints (default: auto-generated by LLM)")
    parser.add_argument("--dry-run",  action="store_true",
                        help="[test] Preview rows, do NOT insert to Supabase")
    parser.add_argument("--limit",    type=int, default=0,
                        help="[test] Max rows to insert (0 = no limit)")
    parser.add_argument("--max-rows-per-dataset", type=int, default=MAX_ROWS_PER_DS,
                        help="[full/test] Max rows to read per dataset (0 = full dataset)")
    parser.add_argument("--retry-failed-only", action="store_true",
                        help="[full] Re-run only dataset slugs recorded in failed_datasets.log")
    parser.add_argument("--retry-report", default="",
                        help="[full] Optional schema validation report JSON to source warn/error slugs")
    args = parser.parse_args()

    google_api_key = os.getenv("GOOGLE_API_KEY")
    supabase_url   = os.getenv("SUPABASE_URL")
    supabase_key   = os.getenv("SUPABASE_KEY")

    if not google_api_key: sys.exit("✗  GOOGLE_API_KEY missing in .env")
    if not supabase_url:   sys.exit("✗  SUPABASE_URL missing in .env")
    if not supabase_key:   sys.exit("✗  SUPABASE_KEY missing in .env")

    ku = os.getenv("KAGGLE_USERNAME", "")
    kk = os.getenv("KAGGLE_KEY", "")
    if ku and kk:
        os.environ["KAGGLE_USERNAME"] = ku
        os.environ["KAGGLE_KEY"]      = kk

    _gemini = genai.Client(api_key=google_api_key)
    _supa   = create_client(supabase_url, supabase_key)
    _runtime_max_rows_per_ds = max(0, args.max_rows_per_dataset)

    if args.test or args.dry_run:
        run_test_mode(args, _gemini, _supa)
    else:
        print("=" * 60)
        print("StoryBit Kaggle Ingestion v6  (LLM auto-metadata)")
        print(f"Spreadsheet: {SPREADSHEET_FILE}")
        print("=" * 60)
        run_full_pipeline(
            _gemini,
            _supa,
            retry_failed_only=args.retry_failed_only,
            retry_report=args.retry_report,
        )
