from __future__ import annotations

from typing import Any


def _segments(pairs: list[tuple[str, float, str]]) -> list[dict[str, Any]]:
    return [{"name": n, "pct": p, "brief": b} for n, p, b in pairs]


TEMPLATE_REGISTRY: dict[str, dict[str, Any]] = {
    # 1. Philosophy & Ideas
    "philosophical_inquiry": {
        "category": "Philosophy & Ideas",
        "name": "Philosophical Inquiry",
        "about": "Explores a big question through layered reasoning.",
        "segments": _segments([
            ("Hook — the question", 0.10, "Open with a provocative question grounded in retrieved evidence."),
            ("Why it matters now", 0.10, "Bridge the abstract idea to current events or lived stakes."),
            ("Historical framing", 0.15, "Trace major schools and shifts in framing over time."),
            ("Core argument", 0.25, "Build a coherent stance from retrieved sources."),
            ("Counterarguments", 0.20, "Steelman opposition using strongest critiques."),
            ("Synthesis", 0.15, "Connect insight to practical implication."),
            ("Closing provocation", 0.05, "Close with an open question."),
        ]),
    },
    "dialectic_debate": {
        "category": "Philosophy & Ideas",
        "name": "Dialectic / Debate Structure",
        "about": "Holds two serious positions in equal tension.",
        "segments": _segments([
            ("Unresolved question", 0.08, "Introduce real disagreement with real consequences."),
            ("Why unresolved", 0.10, "Show structural reasons the debate persists."),
            ("Position A", 0.22, "Present strongest version of A."),
            ("Position B", 0.22, "Present strongest version of B with equal rigor."),
            ("Shared ground", 0.10, "Identify true overlap."),
            ("Core divergence", 0.18, "Isolate the actual crux."),
            ("Viewer decision", 0.07, "Clarify what choice depends on."),
            ("CTA", 0.03, "Invite reasoned viewer response."),
        ]),
    },
    # 2. Psychology & Behaviour
    "psych_concept": {
        "category": "Psychology & Behaviour",
        "name": "Psychological Concept Explainer",
        "about": "Research-grounded explainer for a psych concept.",
        "segments": _segments([
            ("Hook behavior", 0.10, "Describe recognisable behaviour before naming concept."),
            ("Definition", 0.10, "Define concept and origin."),
            ("Research", 0.25, "Walk through key studies and findings."),
            ("Mechanism", 0.20, "Explain cognitive/evolutionary mechanism."),
            ("Real-world effects", 0.20, "Show where it appears in institutions and life."),
            ("Implications", 0.10, "Evidence-based mitigation/application."),
            ("CTA", 0.05, "Prompt observation and discussion."),
        ]),
    },
    "myth_vs_evidence": {
        "category": "Psychology & Behaviour",
        "name": "Psychology Myth vs Evidence",
        "about": "Debunks myths with peer-reviewed evidence.",
        "segments": _segments([
            ("Myth hook", 0.08, "State myth as commonly believed."),
            ("Why spread", 0.12, "Explain social/institutional propagation."),
            ("Myth 1", 0.22, "Claim, evidence, correction."),
            ("Myth 2", 0.22, "Claim, evidence, correction with different evidence type."),
            ("Myth 3", 0.22, "Nuanced partial truth + correction."),
            ("Correct model", 0.09, "Synthesize evidence-based understanding."),
            ("CTA", 0.05, "Invite source-checking."),
        ]),
    },
    # 3. History & Civilisation
    "historical_event": {
        "category": "History & Civilisation",
        "name": "Historical Event Deep-Dive",
        "about": "Narrates event with causal depth and long-run impact.",
        "segments": _segments([
            ("Moment hook", 0.08, "Start at a specific moment."),
            ("World before", 0.15, "Set structural context."),
            ("Trigger and escalation", 0.20, "Trace the causal chain."),
            ("Event arc", 0.25, "Narrate sequence coherently."),
            ("Immediate fallout", 0.15, "Short-run consequences."),
            ("Long legacy", 0.12, "Long-run implications."),
            ("Revisionist lens", 0.05, "Note meaningful disputes."),
        ]),
    },
    "rise_fall": {
        "category": "History & Civilisation",
        "name": "Rise & Fall Arc",
        "about": "Tracks ascent, peak, decay, and collapse dynamics.",
        "segments": _segments([
            ("Hook", 0.08, "Open on peak power paradox."),
            ("Rise", 0.22, "Drivers of ascent."),
            ("Peak", 0.16, "Conditions at maximum influence."),
            ("Cracks", 0.22, "Emerging systemic fragilities."),
            ("Fall", 0.20, "Collapse/decline mechanism."),
            ("Lessons", 0.12, "Transferable structural lesson."),
        ]),
    },
    "primary_source_analysis": {
        "category": "History & Civilisation",
        "name": "Primary Source Analysis",
        "about": "Close-reads key documents and what they reveal.",
        "segments": _segments([
            ("Why doc matters", 0.08, "Set stakes of document."),
            ("Author and context", 0.15, "Who wrote it and under what constraints."),
            ("Close reading", 0.22, "Analyse key passages."),
            ("Silences", 0.18, "What is omitted and why."),
            ("Reception", 0.17, "How contemporaries used/interpreted it."),
            ("Era reveal", 0.12, "What it reveals about the age."),
            ("CTA", 0.08, "Invite primary-source reading."),
        ]),
    },
    # 4. Biography & Legacy
    "public_figure_profile": {
        "category": "Biography & Legacy",
        "name": "Thinker / Public Figure Profile",
        "about": "Profile of life, work, influence, criticism.",
        "segments": _segments([
            ("Relevance hook", 0.08, "Why this figure matters now."),
            ("Formative context", 0.15, "Context shaping worldview."),
            ("Core contribution", 0.35, "2-3 defining pillars."),
            ("Influence", 0.20, "Where impact propagated."),
            ("Criticisms", 0.15, "Blind spots and serious critiques."),
            ("Why still matter", 0.07, "Contemporary relevance."),
        ]),
    },
    "intellectual_legacy": {
        "category": "Biography & Legacy",
        "name": "Intellectual Legacy & Impact",
        "about": "Traces propagation, mutation, and current standing of ideas.",
        "segments": _segments([
            ("Hook", 0.08, "Intention vs later reception."),
            ("Original ideas", 0.12, "Clean baseline of original claims."),
            ("Early reception", 0.15, "First-generation response."),
            ("Mutation", 0.25, "How ideas changed over decades."),
            ("Misreadings", 0.18, "Distortions and controversies."),
            ("Current standing", 0.15, "What scholarship now accepts/rejects."),
            ("CTA", 0.07, "Read originals directly."),
        ]),
    },
    # 5. Science & Technology
    "scientific_controversy": {
        "category": "Science & Technology",
        "name": "Scientific Controversy",
        "about": "Examines real disputes in evolving evidence landscapes.",
        "segments": _segments([
            ("Stake hook", 0.08, "Why this matters outside the lab."),
            ("Dispute definition", 0.12, "What exactly is contested."),
            ("Consensus case", 0.18, "Best current consensus evidence."),
            ("Dissent case", 0.18, "Strongest dissent evidence."),
            ("Why persists", 0.18, "Method and incentive reasons."),
            ("What resolves", 0.16, "Evidence needed to settle dispute."),
            ("CTA", 0.10, "Point to primary literature."),
        ]),
    },
    "tech_impact_assessment": {
        "category": "Science & Technology",
        "name": "Technology Impact Assessment",
        "about": "Assesses adoption, benefits, harms, and governance.",
        "segments": _segments([
            ("Disruption hook", 0.08, "Documented disruption already visible."),
            ("Tech explained", 0.12, "Plain-language mechanism."),
            ("Adoption state", 0.12, "Who uses it and where."),
            ("Positive effects", 0.18, "Measured benefits."),
            ("Negative effects", 0.20, "Measured harms/risks."),
            ("Governance", 0.18, "Policy/regulatory responses."),
            ("Watchlist", 0.08, "Indicators for next 5 years."),
            ("CTA", 0.04, "Primary source follow-up."),
        ]),
    },
    # 6. Economics & Society
    "economic_phenomenon": {
        "category": "Economics & Society",
        "name": "Economic Phenomenon Explainer",
        "about": "Explains macro force via data, causes, and distributional impact.",
        "segments": _segments([
            ("Lived hook", 0.08, "Start with lived economic pain/gain."),
            ("Data baseline", 0.15, "Establish measurements over time."),
            ("Structural causes", 0.22, "Main causal drivers."),
            ("Winners/losers", 0.18, "Distributional effects."),
            ("Historical analogues", 0.15, "Comparable prior episodes."),
            ("Policy response", 0.15, "Current interventions and limits."),
            ("CTA", 0.07, "Point to primary data sources."),
        ]),
    },
    "social_trend_investigation": {
        "category": "Economics & Society",
        "name": "Social Trend Investigation",
        "about": "Investigates major social shift from signal to structure.",
        "segments": _segments([
            ("Signal hook", 0.08, "Document one key shift signal."),
            ("Scale", 0.14, "How large/deep is the trend."),
            ("Drivers", 0.22, "Deep causal forces."),
            ("Differential impact", 0.16, "Who is affected differently."),
            ("Counterforces", 0.14, "What pushes back against trend."),
            ("Trajectories", 0.16, "Likely medium-term outcomes."),
            ("CTA", 0.10, "Point to longitudinal trackers."),
        ]),
    },
    # 7. Analysis & Breakdowns
    "systems_breakdown": {
        "category": "Analysis & Breakdowns",
        "name": "Systems / Mechanisms Breakdown",
        "about": "Deconstructs a complex system layer by layer.",
        "segments": _segments([
            ("Output hook", 0.08, "Start from visible output."),
            ("System boundary", 0.10, "Define boundaries and components."),
            ("Input layer", 0.18, "Map key inputs."),
            ("Processing layer", 0.22, "Explain transformation rules."),
            ("Output layer", 0.18, "Intended and unintended outputs."),
            ("Failure modes", 0.14, "Capture and breakpoints."),
            ("Intervention logic", 0.07, "What changes if one part shifts."),
            ("CTA", 0.03, "Audience-relevant takeaway."),
        ]),
    },
    "comparative_analysis": {
        "category": "Analysis & Breakdowns",
        "name": "Comparative Analysis",
        "about": "Structured parallel comparison across multiple dimensions.",
        "segments": _segments([
            ("Paradox hook", 0.10, "Lead with counterintuitive contrast."),
            ("Why compare", 0.10, "Justify pairing."),
            ("Dimension 1", 0.20, "Parallel evidence on axis 1."),
            ("Dimension 2", 0.20, "Parallel evidence on axis 2."),
            ("Dimension 3", 0.20, "Parallel evidence on nuance axis."),
            ("Pattern", 0.15, "Higher-order synthesis."),
            ("Limits", 0.05, "Confounders and caveats."),
        ]),
    },
    "data_investigation": {
        "category": "Analysis & Breakdowns",
        "name": "Data Investigation",
        "about": "Single number/dataset drives the full inquiry.",
        "segments": _segments([
            ("Number hook", 0.08, "Open with one striking statistic."),
            ("Data provenance", 0.14, "Who collected and how."),
            ("Metric meaning", 0.16, "What it measures and misses."),
            ("Trendline", 0.18, "How metric changed over time."),
            ("Causal inquiry", 0.22, "Why metric looks this way."),
            ("Blind spots", 0.14, "What the number conceals."),
            ("CTA", 0.08, "Point to the dataset directly."),
        ]),
    },
    # 8. News & Contemporary Events
    "news_explainer": {
        "category": "News & Contemporary Events",
        "name": "News Explainer (Context-First)",
        "about": "Explains beyond headline: causes, actors, likely paths.",
        "segments": _segments([
            ("Headline hook", 0.08, "What happened, clearly."),
            ("Backstory", 0.18, "Conditions that made event possible."),
            ("Actors", 0.17, "Who is involved and incentives."),
            ("Data view", 0.17, "Ground claims in numbers."),
            ("Narratives", 0.15, "Competing framings and differences."),
            ("Scenarios", 0.15, "Plausible next trajectories."),
            ("Why viewer care", 0.07, "Personal/civic/economic stake."),
            ("CTA", 0.03, "Primary source to follow."),
        ]),
    },
    "policy_breakdown": {
        "category": "News & Contemporary Events",
        "name": "Policy / Legislation Breakdown",
        "about": "Decodes policy text, stakeholders, and likely effects.",
        "segments": _segments([
            ("Human hook", 0.08, "Concrete impact first."),
            ("Policy text decoded", 0.18, "What it says in plain language."),
            ("Proponents", 0.15, "Who supports and why."),
            ("Opposition", 0.15, "Who resists and why."),
            ("Comparable evidence", 0.20, "Similar policy outcomes elsewhere."),
            ("Likely effects", 0.14, "Evidence-backed projection."),
            ("Watchlist", 0.07, "Implementation signals."),
            ("CTA", 0.03, "Official text link prompt."),
        ]),
    },
    "investigative_deep_dive": {
        "category": "News & Contemporary Events",
        "name": "Investigative Deep-Dive",
        "about": "Builds multi-thread evidence toward structural conclusion.",
        "segments": _segments([
            ("Anomaly hook", 0.08, "Present observed anomaly."),
            ("Official story", 0.10, "State baseline account fairly."),
            ("Evidence thread 1", 0.18, "Document/data contradiction."),
            ("Evidence thread 2", 0.18, "Comparative/historical pattern."),
            ("Evidence thread 3", 0.18, "Structural mechanism."),
            ("Synthesis", 0.16, "What evidence collectively indicates."),
            ("Accountability", 0.08, "Institutional response gaps."),
            ("CTA", 0.04, "Primary trail to inspect."),
        ]),
    },
    # 9. Thought Leadership & Discussion
    "big_idea": {
        "category": "Thought Leadership & Discussion",
        "name": "Big Idea / Thesis Essay",
        "about": "Advances a thesis with multi-pillar evidence.",
        "segments": _segments([
            ("Thesis drop", 0.08, "State thesis boldly."),
            ("Conventional view", 0.12, "Steelman mainstream view."),
            ("Pillar 1", 0.20, "Evidence leg one."),
            ("Pillar 2", 0.20, "Evidence leg two from another domain."),
            ("Pillar 3", 0.15, "Nuanced/surprising evidence."),
            ("Counterargument", 0.15, "Address strongest objection."),
            ("Implication", 0.07, "So-what for action/thought."),
            ("CTA", 0.03, "Invite critical response."),
        ]),
    },
    "future_scenario": {
        "category": "Thought Leadership & Discussion",
        "name": "Future / Scenario Analysis",
        "about": "Explores plausible trajectories over medium horizon.",
        "segments": _segments([
            ("Signal hook", 0.08, "Concrete acceleration signal."),
            ("Baseline", 0.15, "Current state and constraints."),
            ("Driving forces", 0.17, "What pushes trend forward."),
            ("Scenario A", 0.18, "Optimistic path."),
            ("Scenario B", 0.18, "Pessimistic path."),
            ("Scenario C", 0.14, "Most likely messy middle."),
            ("Implication now", 0.07, "Actionable now."),
            ("CTA", 0.03, "Follow forecast sources."),
        ]),
    },
    "cross_disciplinary_synthesis": {
        "category": "Thought Leadership & Discussion",
        "name": "Cross-Disciplinary Synthesis",
        "about": "Connects two fields to reveal third-order insight.",
        "segments": _segments([
            ("Connection hook", 0.08, "Unexpected bridge between fields."),
            ("Field A concept", 0.16, "Explain source concept clearly."),
            ("Field B puzzle", 0.16, "Define unsolved problem in target field."),
            ("Bridge mapping", 0.22, "Map structures precisely."),
            ("New insight", 0.20, "Show third insight from synthesis."),
            ("Limits", 0.12, "Where analogy fails."),
            ("CTA", 0.06, "Invite experts from both fields."),
        ]),
    },
    # 10. Motivational & Inspirational
    "evidence_based_motivational": {
        "category": "Motivational & Inspirational",
        "name": "Evidence-Based Motivational",
        "about": "Motivation grounded in behavioral evidence.",
        "segments": _segments([
            ("Gap hook", 0.08, "Transformation gap stated concretely."),
            ("Research base", 0.15, "What evidence says about change."),
            ("Documented case", 0.20, "Real case, no fabrication."),
            ("Mechanism", 0.18, "Why change worked."),
            ("Obstacle", 0.17, "Common blockers from evidence."),
            ("Actionable frame", 0.15, "One practical lens."),
            ("Closing charge", 0.07, "Evidence-earned motivation."),
        ]),
    },
    "idea_that_changed_everything": {
        "category": "Motivational & Inspirational",
        "name": "Idea That Changed Everything",
        "about": "Tracks one idea and measurable impact over time.",
        "segments": _segments([
            ("Before/after hook", 0.08, "World before vs after idea."),
            ("Idea plainly", 0.12, "State core claim simply."),
            ("Origin", 0.15, "Who/why it emerged."),
            ("Resistance", 0.12, "Initial rejection."),
            ("Spread", 0.18, "How adoption happened."),
            ("Impact", 0.20, "Measured impact."),
            ("Still true?", 0.10, "What held up/changed."),
            ("CTA", 0.05, "Read original source."),
        ]),
    },
    "failure_autopsy": {
        "category": "Motivational & Inspirational",
        "name": "Failure Autopsy",
        "about": "Dissects failure to extract transferable principles.",
        "segments": _segments([
            ("Failure moment", 0.08, "Start at break point."),
            ("Stakes", 0.10, "What was on the line."),
            ("Wrong turn 1", 0.18, "First key bad decision."),
            ("Compounding error", 0.18, "Second lock-in decision."),
            ("Systemic factors", 0.18, "Structural contributors."),
            ("Post-mortem findings", 0.14, "Forensic conclusions."),
            ("Transfer principle", 0.10, "Generalizable lesson."),
            ("CTA", 0.04, "Point to full post-mortem."),
        ]),
    },
    # 26th universal fallback template
    "general_explainer": {
        "category": "Universal",
        "name": "General Explainer",
        "about": "Universal fallback when signals are sparse.",
        "segments": _segments([
            ("Hook", 0.10, "Define the central tension quickly."),
            ("Context", 0.20, "Set historical and structural background."),
            ("Evidence", 0.30, "Present strongest supporting evidence."),
            ("Counterpoint", 0.20, "Address strongest counterargument."),
            ("Implication", 0.15, "Explain what changes for viewer."),
            ("CTA", 0.05, "Offer next investigation step."),
        ]),
    },
}
